export default [
    {
        id: 1,
        name: "Alex",
        description: "I am here to teach you",
        imageUrl: "/profile.jpg",
        link: "https://example.com",
        buttonText: "Contact",
        skills: ["java","python"],
        rating: 9.8,
    },
    {
        id: 2,
        name: "Bruno",
        description: "I am here to teach you",
        imageUrl: "/profile.jpg",
        link: "https://example.com",
        buttonText: "Contact",
        skills: ["React","Java"],
        rating: 9.8,
    },
    {
        id: 3,
        name: "Carol",
        description: "I am here to teach you",
        imageUrl: "/profile.jpg",
        link: "https://example.com",
        buttonText: "Contact",
        skills: ["React","python"],
        rating: 9.8,
    },
    {
        id: 4,
        name: "Derek",
        description: "I am here to teach you",
        imageUrl: "/profile.jpg",
        link: "https://example.com",
        buttonText: "Contact",
        skills: ["java","Web Development"],
        rating: 9.8,
    },
    {
        id: 5,
        name: "Derek",
        description: "I am here to teach you",
        imageUrl: "/profile.jpg",
        link: "https://example.com",
        buttonText: "Contact",
        skills: ["java","python"],
        rating: 9.8,
    }
]